### PR TITLE
[compat] Drop support of PY2

### PR DESCRIPTION
**Pull request by Djailla**
Allowing to drop six requirement

### CODE REVIEW

**Comment by Djailla** [comment]
Hello @Julian 

The CI is marked as red due to coverage, but you could be interested ?

**Comment by Julian** [comment]
@Djailla hi! Yes, thanks for sending it.

This likely is something I'll want to do in the next few months, but there's likely a few things higher on the list for limited time :/ -- the one thing I see is we need to set a `python_requires` in the `setup.cfg` as part of this change, so that we don't break Python 2 for any existing versions.

But beyond that yes would be interested, just may take me a bit to get to this.

Thanks for sending it!

**Comment by Julian** [comment]
Merged, thanks!

**Comment by sloanlance** [comment]
Awesome!  This solves a lot of the headaches I was having with #708!

**Pull request merged**
