### PR TITLE
docs: faq: Updates to extend_with_default() example

### PR DESCRIPTION
**Pull request by stuarteberg**
The FAQ explains that one could (in theory) write a schema in which default values aren't valid under their own schema, and then goes on to present some example code that would allow such a use-case.

Fair enough, but I think most users would rather have an example that actually *does* validate the defaults.  Plus, if the default values are added to the instance *before* validation, then entire objects can be provided with default contents, even if the object was missing from the instance entirely.  (The updated FAQ text in this PR provides an example.)

### CODE REVIEW

**Comment by stuarteberg** [comment]
In case it's helpful, you can view a pretty version of the new doc text here:
http://stuarteberg.github.io/jsonschema/faq.html#why-doesn-t-my-schema-that-has-a-default-property-actually-set-the-default-on-my-instance

**Comment by Julian** [comment]
Cool, thanks! Doc improvements are very much appreciated. I haven't read through this yet, but FWIW, I really don't recommend doing `default` setting during validation at all -- I forget whether that's mentioned in that part of the FAQ.

But I'll have a read through, thanks again!

**Comment by stuarteberg** [comment]
>FWIW, I really don't recommend doing default setting during validation at all

Indeed, your text mentions that, and I didn't change it (I only added text).  I know default-setting isn't great for all use-cases, but I still *really* appreciate that you gave an example in the FAQ.  My only problem with the example code was that it didn't work with nested objects out-of-the-box.  By swapping a few lines, now it does.

**Comment by Julian** [comment]
Cool, looks good, appreciated.

**Pull request merged**
