### PR TITLE
Minor fix in ErrorTree for multiple errors on different levels.

### PR DESCRIPTION
**Pull request by joepvandijken**
https://github.com/Julian/jsonschema/issues/283

### CODE REVIEW

**Comment by joepvandijken** [comment]
If anyone will verify this is an actual bug, I will also try to add a regression test for this case. Currently both versions pass all tests.

**Comment by Julian** [comment]
Great, thanks! This does seem likely to be correct. A test would be great.

**Comment by joepvandijken** [comment]
If you have any comments on the code let me know, I'm happy to address those.

**Comment by Julian** [comment]
Thanks so much! I'll try to have a look in the next day or two and leave any comments.

**Comment by Julian** [comment]
So sorry that this slipped so long. I have a comment or two, mainly revolving around that it'd be nice to try to use "real" looking data rather than "i1" and "i2", but despite that, I think the real solution is going to be whenever I have the time to make jsonschema's test suite use hypothesis (which at the current pace is far off :().

But it's certainly good enough to merge, and I'm sorry again about the wait.

**Pull request merged**
