### PR TITLE
Add Benchmarks & Split/Unroll-scopes optimizations (x1.6 faster)

### PR DESCRIPTION
**Pull request by ankostis**
For issue #158:

1. ``benchmark`` branch: Added a benchmark with meta_schemas cheking & extensive sample-schema with references.
2. Implemented two optimizations:
    2.a. ``split_scopes`` branch: Keep URIs in 2 parts (url, fragment) to avoid fragging/defragging since fragments do not join, they always override (~1.1 faster)
    2.b. ``unroll_scopes`` branch:  Replace resolver.in_scope() context-manager with a push/pop stack of scopes, that does nothing it when no ``id`` property exists (~1.5 faster).
3. ``split_unroll_scopes`` branch: Combined both optimizations (~1.6 faster).
3. For future reference, the timed-results are engraved on the respective methods of ``wltp/test/test_benchmarks.py`` TC (unfortunately they are host-specific).

ALL TCs RUN AS OK (apart from split_frags which was post-edited on the combined branch)

### CODE REVIEW

**Comment by dnephin** [comment]
This changes improve the performance on my benchmark by nearly 2x.  

What can I do to help get this merged?  It looks like the tests are failing and it needs to be rebased with msater.

**Comment by cgurnik** [comment]
@Julian Would it be possible for you to take a look at this branch? Our project has a relatively simple schema, and validation using jsonschema is frequently the slowest part of our code. A performance increase of 2x would be a significant benefit to us. As @dnephin mentioned, what can I do to help get this merged in?

**Comment by Julian** [comment]
Hi @cgurnik -- @dnephin already successfully managed to get in some performance changes -- can you give your project a shot on current master and see if you get any difference?

I'm trying to find some time to do a release but I was overseas for a few days.

If you don't see results can you possibly include some profiling output, would love to have a look!

**Comment by dnephin** [comment]
Most of the changes from this branch were included in my branch, so it might even be appropriate to close this one.

**Comment by ankostis** [comment]
@dnephin Do you mean that this dnephin@1c15827713cbcf43c4fac8cfa9e5c3e50a501e96 (branch: `perf_take2`) contains roughly the 2 perf-improvements, but not #184?

**Comment by dnephin** [comment]
Right, I included many of them in https://github.com/dnephin/jsonschema/commit/2fda1556ef7714d562317049f46db6ff59db5c2f

**Pull request closed without merging**
