### PR TITLE
Eterna2/fix relative ref

### LINKED ISSUE #570: "RefResolutionError" exception raised when resolving "$ref"
Taking the example from the json-schema documentation on structuring complex schema: [https://json-schema.org/understanding-json-schema/structuring.html](url).

I create a file **address_pass.json** where address is defined internally:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "#/definitions/address" },
    "shipping_address": { "$ref": "#/definitions/address" }
  }
}
```
The code below illustrates this validates the example instance:
```python
import json
from jsonschema import validate

instance = {
  "shipping_address": {
    "street_address": "1600 Pennsylvania Avenue NW",
    "city": "Washington",
    "state": "DC"
  },
  "billing_address": {
    "street_address": "1st Street SE",
    "city": "Washington",
    "state": "DC"
  }
}

with open('address_pass.json') as json_data:
    schema = json.load(json_data)
    json_data.close()
    
validate(instance=instance, schema=schema)
```
All good. Now, the example does not define the content of **definitions.json** but I believe it should look like this:
```
{
  "address": {
    "type": "object",
    "properties": {
      "street_address": { "type": "string" },
      "city":           { "type": "string" },
      "state":          { "type": "string" }
    },
    "required": ["street_address", "city", "state"]
  }
}
```
With corresponding reference from within **address_fail.json** as below:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "definitions.json#/address" },
    "shipping_address": { "$ref": "definitions.json#/address" }
  }
}
```
However, the same code as above now fails with the RefResolutionError reported above:
```python
import json
from jsonschema import validate

instance = {
  "shipping_address": {
    "street_address": "1600 Pennsylvania Avenue NW",
    "city": "Washington",
    "state": "DC"
  },
  "billing_address": {
    "street_address": "1st Street SE",
    "city": "Washington",
    "state": "DC"
  }
}

with open('address_fail.json') as json_data:
    schema = json.load(json_data)
    json_data.close()
    
validate(instance=instance, schema=schema)
```
Furthermore, replacing ```$ref``` with ```file``` and a full path to **definitions.json**  illustrates the external reference does work. So the issue seems to be simply in locating the file.

### PR DESCRIPTION
**Pull request by eterna2**
Fix #570 
- Support relative local fs ref
- Support relative remote ref
- Added corresponding unittests

### CODE REVIEW

**Comment by eterna2** [comment]
can't figure out why coverage for diff is not 100%. My 2nd unit test shld have covered it.

**Comment by Julian** [comment]
Thanks a lot for trying to tackle this!

Does this work properly with requests?

If so, I'm really more inclined at this point to just drop support for urllib entirely and make requests fully required -- the conditional dependency is... like 7 years old at this point, back when it wasn't necessarily the case that requests was a good idea to depend on.

**Comment by eterna2** [comment]
@Julian 

Actually, my implementation does not use request (but there is no issue using request either). 

It is more of a fallback logic (cuz I do not want to change too much of ur code), it will only attempt to try:
- resolve as a local relative path (concat `base_uri` with `ref_uri` and try `json.load`).
- otherwise resolve as remote relative path (strip spec filename to get base url and resolve path with relative `ref_uri` with respect to the base url (I use urllib/urlopen here in this case) - but i still need urlsplit and urlunsplit to interpret the url so that I can find the base_url. But frankly it is not difficult to just implement that part (instead of using urllib).

```py
 # need to reimplement this if u r deprecating urllib
scheme, network, path, qs, frag = urlsplit(self.base_uri) 

path = "/".join(path.split("/")[0:-1])  # base path

 # need to reimplement this if u r deprecating urllib
base_url = urlunsplit((scheme, network, path, qs, frag)) 

# this part can be easily replaced with request instead
with urlopen(urljoin(base_url, uri)) as url:
  result = json.loads(url.read().decode("utf-8"))
```

I made this PR with minimal change to ur codebase. 


Ideally, if u are going to deprecate `urllib` we simplify the RefResolver alot by only using ur existing custom_handlers hook - i.e. we can write a few default handlers (http/https, file, relative_file, relative_remote) and has a fallback instead of a dict (i.e. a list instead of dict only)

This is not working code, just my 2cents, if u ever going to do any major refractoring.

```py
handlers_fallback = [std_handler, relative_file_handler, relative_remote_handler]

def get_std_handlers(uri, custom_handlers={}):
  if uri[0] == "#":
    return local_ref_handler
  if uri[0:7] == "http://" or uri[0:8] == "https://":
    return request_handler

   return custom_handlers.get(schema, file_handler)

def request_handler(uri, base_uri=""):
  return request.get(uri).json()

def std_handler(uri, base_uri=""):
  handler = get_std_handlers(uri)
  try:
    if handler:
      return handler(uri, base_uri=base_uri)
  except Exception:
    return file_handler(uri, base_uri=base_uri)

def local_ref_handler(uri, base_uri=""):
  return definitions[_get_definition_key(uri)]

def file_handler(uri, base_uri=""):
  file_path = strip_protocol_if_any(uri)
  with open(file_path) as fin:  
    return json.load(fin)
 
def relative_file_handler(uri, base_uri=""):
  ref_path = os.path.join(strip_protocol_if_any(base_uri), strip_protocol_if_any(uri))
  return file_handler(ref_path)

def relative_remote_handler(uri, base_uri=""):
  base_url = get_base_url(base_uri)
  url = "%s/%s" % (base_url, strip_protocol_if_any(uri))
  return request_handler(url)
  
def handle_ref(handlers, handler_kwargs, index=0):
  if index >= len(handlers):
    raise Exception("Unable to resolve ref")
  try:
    return handlers[index](**handler_kwargs)
  except Exception:
    return handle_ref(handlers, handler_kwargs, index=index+1)

```

**Comment by Julian** [comment]
> Actually, my implementation does not use request (but there is no issue using request either).

Sorry so are you saying then that the issue doesn't exist when requests is installed?

I'm not sure I follow the rest of your comment, since:

> Just my 2 cent, if u are going to deprecate urllib and do some major refractoring, can make use of the existing custom_handler hook - i.e. create a http/https handler, file handler.

That wouldn't be any major refactoring, it'd literally just delete the entire `else` block you modified here, but otherwise everything stays exactly the same -- so basically what I'm asking is "in that case, is whatever bug you're trying to fix still present"?

**Comment by Julian** [comment]
I should say I'm separately not very keen to do any kind of fallback logic / chaining -- it's easy to tell what's a remote ref and what's a local one, so we shouldn't really need any try/excepting or if/elsing, so will need to try to understand what the motivation is there.

**Comment by Julian** [comment]
This also looks pretty similar to #531, where I seem to have asked the exact same question :)

**Comment by eterna2** [comment]
@Julian 

This is different from #531. #531 is asking to support `file://`.  #570 is asking to support relative reference.

The use case is mostly when u do not want to publish ur schema (i.e. http/https) and only wish to retrieve it from local fs. `urllib` supports `file://` but this is not ideal, as it requires absolute path which is not desirable as different machine will have different paths.

So the feature request is:

if `$ref = "some_schema.json#some_definition"`, `RefResolver` should load from local fs relative to where the original schema (i.e. `$schema`) resides in the fs. If `$schema` is in some remote endpoint, it should similar load relative from that remote endpoint.

The current implementation does not support this:
- request only target http/https (no fs or file:// at all)

And  there are multiple ways to go about doing this:
- u can check `$ref` to see if http/https is specified and use request.
- unless u r dropping `file://` support (it is currently supported because of `urlopen`), you will need to do a check for this too, and implement an equivalent without using `urlopen`.
- then u need to do a check if the original json schema is http/https or a local fs, then implement a local relative `json.load`, or a `request.get(base_url+url).json()` respectively. 

or u can just do a fallack, which i did in this PR. The relative ref will never hit ur request `if` statement because it is relative ref (e.g. `some_spec.json#some_def` instead of `http://foo.bar/some_spec.json#some_def`).

**Comment by Julian** [comment]
Got it thanks -- that makes sense, but is this really that hard to do currently? If it's really just for development, just invent your own scheme, and include a handler for it?

I.e.:

```
import json
from jsonschema import RefResolver, validate


def relative(url):
    _, _, path = url.partition("://")
    with open(path) as file:
        return json.load(file)


with open("schema.json") as file:
    schema = json.load(file)
    resolver = RefResolver.from_schema(schema, handlers={"relative-file": relative})
    validate("", schema, resolver=resolver)
```

**Comment by eterna2** [comment]
This is a PR. U can see my fix here. It isn't hard, and it is officially in the spec (relative ref I mean).

Your approach is doable but not elegant, as in it feels hackish. Cuz the main use case here is validation as part of our unit test/ci process. Would be hackish if we write a custom handler with a custom protocol for all our projects just to support relative ref.

Regardless of urllib support of otherwise, the fix is relatively simple, it is just falling back to local relative fs -> remote relative fs. All about path manipulation, not much on io.

**Comment by Julian** [comment]
The behavior in the PR is definitely not in the spec, so I'm trying to narrow down exactly what/which issue *is* in the spec that you're trying to fix here.

The spec definitely does not say "every time you see a ref, try cascading through first resolving it absolutely, then assume it's a local path, ..."

It has rules about what you assume the base URI is for schemas that forgot to declare it, so fully believe there's something to fix there, but yeah that's what I was referring to above about not having fallback behavior.

**Comment by Julian** [comment]
The other thing I meant to mention here is whether you're really asking about loading schemas that don't specify their base URI and then not telling `jsonschema` what that base URI is that you loaded them from. E.g.:

```
import os
import json
from jsonschema import RefResolver, validate


with open("schema.json") as file:
    schema = json.load(file)
    resolver = RefResolver(
        referrer=schema,
        base_uri="file://" + os.getcwd() + "/",
    )
    validate("", schema, resolver=resolver)
```

if you want the base URI to resolve relative to the current working directory, or some other one.
```

**Comment by eterna2** [comment]
Yeah this is what I meant and needed. Thanks!

Will this work recursively? As in this schema loads another schema which loads another schema? All the schemas are in the same folder but does not have a $id defined.

Because my usecase is a pretty complex set of config files that I need to validate for multiple projects.

**Comment by Julian** [comment]
Yes it will, that's a global base URI to apply.

**Pull request closed without merging**
