### PR TITLE
Use importlib from stdlib (if possible)

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by Julian** [comment]
Great, thanks!

**Comment by 4383** [comment]
Hello,

I still have the an issue with `jsonschema` and `importlib` under python 3.8, I seen these changes was released with jsonschema 3.2.0 so I expected that this version solve my issue with py38 but it's not the case.

```
python3.8 -m pip install --user jsonschema
Collecting jsonschema                                                                                                                                                                                                
  Using cached https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from jsonschema)                                                                                                                                                                           
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.11.0 in ./.local/lib/python3.8/site-packages (from jsonschema) (1.13.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from jsonschema) (40.6.2)
Collecting pyrsistent>=0.14.0 (from jsonschema)                                                           
Installing collected packages: attrs, pyrsistent, jsonschema              
Successfully installed attrs-19.3.0 jsonschema-3.2.0 pyrsistent-0.16.0
You are using pip version 18.1, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ python3.8                                                                        
Python 3.8.0a0 (heads/master:57dd79e6f7, May 17 2019, 13:04:54) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.                                
>>> import jsonschema             
Traceback (most recent call last):                                                                                                                                                                                   
  File "~/.local/lib/python3.8/site-packages/jsonschema/__init__.py", line 31, in <module>
    from importlib import metadata                                                                        
ImportError: cannot import name 'metadata' from 'importlib' (/usr/local/lib/python3.8/importlib/__init__.py)
                                                     
During handling of the above exception, another exception occurred:
                                                                                                          
Traceback (most recent call last):       
  File "<stdin>", line 1, in <module>                                                                     
  File "/home/hberaud/.local/lib/python3.8/site-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

Maybe I missed something, any idea?

**Comment by Julian** [comment]
Your Python seems broken. Where did you get it? Try just `from importlib import metadata` in a REPL -- if it doesn't work, wherever you got the Python from has miscompiled it.

**Comment by Julian** [comment]
Oh. You're on an alpha, so probably that's your issue.

**Comment by 4383** [comment]
Oh right good catch, thanks @Julian

**Comment by 4383** [comment]
I confirm that moving away from the alpha version fix the issue.

Thanks

**Pull request merged**
